### ISSUE TITLE
NullPointerException when run g.V.count() on Redhat Linux, but works fine on Ubuntu

### ISSUE THREAD

**Issue by wanghaifeng** [thinkaurelius/faunus#103]
I got NPE when run g.V.count() on RHEL server but on Ubuntu, the command works fine.
Servers: Redhat Linux 6.2 x86_64  and  Ubuntu x86_64
Issues:

``` java
gremlin> g.V.count()
13/03/01 04:35:33 INFO mapreduce.FaunusCompiler: Compiled to 1 MapReduce job(s)
13/03/01 04:35:33 INFO mapreduce.FaunusCompiler: Executing job 1 out of 1: MapSequence[com.thinkaurelius.faunus.mapreduce.transform.VerticesMap.Map, com.thinkaurelius.faunus.mapreduce.util.CountMapReduce.Map, com.thinkaurelius.faunus.mapreduce.util.CountMapReduce.Reduce]
13/03/01 04:35:33 INFO mapreduce.FaunusCompiler: Job data location: output/job-0
13/03/01 04:35:33 WARN util.NativeCodeLoader: Unable to load native-hadoop library for your platform... using builtin-java classes where applicable
13/03/01 04:35:33 WARN mapred.JobClient: Use GenericOptionsParser for parsing the arguments. Applications should implement Tool for the same.
13/03/01 04:35:34 INFO impl.ConnectionPoolMBeanManager: Registering mbean: com.netflix.MonitoredResources:type=ASTYANAX,name=TitanConnectionPool,ServiceType=connectionpool
13/03/01 04:35:34 WARN idassigner.VertexIDAssigner: ID Partitioning is disabled which will likely cause uneven data distribution
13/03/01 04:35:35 INFO mapred.JobClient: Running job: job_local_0001
13/03/01 04:35:35 INFO util.ProcessTree: setsid exited with exit code 0
13/03/01 04:35:35 INFO mapred.Task:  Using ResourceCalculatorPlugin : org.apache.hadoop.util.LinuxResourceCalculatorPlugin@49c1f0e7
13/03/01 04:35:35 WARN idassigner.VertexIDAssigner: ID Partitioning is disabled which will likely cause uneven data distribution
13/03/01 04:35:35 INFO mapred.MapTask: io.sort.mb = 100
13/03/01 04:35:36 INFO mapred.MapTask: data buffer = 79691776/99614720
13/03/01 04:35:36 INFO mapred.MapTask: record buffer = 262144/327680
13/03/01 04:35:36 ERROR impl.ConnectionPoolMBeanManager: com.netflix.MonitoredResources:type=ASTYANAX,name=TitanConnectionPool,ServiceType=connectionpool
13/03/01 04:35:36 INFO mapred.MapTask: Starting flush of map output
13/03/01 04:35:36 INFO compress.CodecPool: Got brand-new compressor
13/03/01 04:35:36 INFO mapred.Task: Task:attempt_local_0001_m_000000_0 is done. And is in the process of commiting
13/03/01 04:35:36 INFO mapred.JobClient:  map 0% reduce 0%
13/03/01 04:35:38 INFO mapred.LocalJobRunner:
13/03/01 04:35:38 INFO mapred.Task: Task 'attempt_local_0001_m_000000_0' done.
13/03/01 04:35:38 INFO mapred.Task:  Using ResourceCalculatorPlugin : org.apache.hadoop.util.LinuxResourceCalculatorPlugin@233e7424
13/03/01 04:35:38 INFO impl.ConnectionPoolMBeanManager: Registering mbean: com.netflix.MonitoredResources:type=ASTYANAX,name=TitanConnectionPool,ServiceType=connectionpool
13/03/01 04:35:38 WARN idassigner.VertexIDAssigner: ID Partitioning is disabled which will likely cause uneven data distribution
13/03/01 04:35:38 INFO mapred.MapTask: io.sort.mb = 100
13/03/01 04:35:38 INFO mapred.MapTask: data buffer = 79691776/99614720
13/03/01 04:35:38 INFO mapred.MapTask: record buffer = 262144/327680
13/03/01 04:35:39 WARN mapred.LocalJobRunner: job_local_0001
java.lang.NullPointerException
        at com.thinkaurelius.titan.graphdb.database.StandardTitanGraph.readInline(StandardTitanGraph.java:410)
        at com.thinkaurelius.titan.graphdb.database.StandardTitanGraph.loadRelations(StandardTitanGraph.java:347)
        at com.thinkaurelius.faunus.formats.titan.cassandra.FaunusTitanCassandraGraph.readFaunusVertex(FaunusTitanCassandraGraph.java:38)
        at com.thinkaurelius.faunus.formats.titan.cassandra.TitanCassandraRecordReader.nextKeyValue(TitanCassandraRecordReader.java:38)
        at org.apache.hadoop.mapred.MapTask$NewTrackingRecordReader.nextKeyValue(MapTask.java:532)
        at org.apache.hadoop.mapreduce.MapContext.nextKeyValue(MapContext.java:67)
        at org.apache.hadoop.mapreduce.Mapper.run(Mapper.java:143)
        at org.apache.hadoop.mapred.MapTask.runNewMapper(MapTask.java:764)
        at org.apache.hadoop.mapred.MapTask.run(MapTask.java:370)
        at org.apache.hadoop.mapred.LocalJobRunner$Job.run(LocalJobRunner.java:212)
13/03/01 04:35:39 INFO mapred.JobClient:  map 100% reduce 0%
13/03/01 04:35:39 INFO mapred.JobClient: Job complete: job_local_0001
13/03/01 04:35:39 INFO mapred.JobClient: Counters: 15
13/03/01 04:35:39 INFO mapred.JobClient:   File Input Format Counters
13/03/01 04:35:39 INFO mapred.JobClient:     Bytes Read=0
13/03/01 04:35:39 INFO mapred.JobClient:   FileSystemCounters
13/03/01 04:35:39 INFO mapred.JobClient:     FILE_BYTES_READ=46395120
13/03/01 04:35:39 INFO mapred.JobClient:     FILE_BYTES_WRITTEN=46797084
13/03/01 04:35:39 INFO mapred.JobClient:   Map-Reduce Framework
13/03/01 04:35:39 INFO mapred.JobClient:     Map output materialized bytes=14
13/03/01 04:35:39 INFO mapred.JobClient:     Combine output records=0
13/03/01 04:35:39 INFO mapred.JobClient:     Map input records=0
13/03/01 04:35:39 INFO mapred.JobClient:     Physical memory (bytes) snapshot=0
13/03/01 04:35:39 INFO mapred.JobClient:     Spilled Records=0
13/03/01 04:35:39 INFO mapred.JobClient:     Map output bytes=0
13/03/01 04:35:39 INFO mapred.JobClient:     Total committed heap usage (bytes)=235012096
13/03/01 04:35:39 INFO mapred.JobClient:     CPU time spent (ms)=0
13/03/01 04:35:39 INFO mapred.JobClient:     Virtual memory (bytes) snapshot=0
13/03/01 04:35:39 INFO mapred.JobClient:     SPLIT_RAW_BYTES=67
13/03/01 04:35:39 INFO mapred.JobClient:     Map output records=0
13/03/01 04:35:39 INFO mapred.JobClient:     Combine input records=0
13/03/01 04:35:39 ERROR mapreduce.FaunusCompiler: Faunus job error -- remaining MapReduce jobs have been canceled
gremlin> exit

```

Another NPE output:

``` java
13/03/01 04:36:08 WARN mapred.LocalJobRunner: job_local_0001
java.lang.NullPointerException
        at com.thinkaurelius.titan.graphdb.database.StandardTitanGraph.readInline(StandardTitanGraph.java:410)
        at com.thinkaurelius.titan.graphdb.database.StandardTitanGraph.loadRelations(StandardTitanGraph.java:347)
        at com.thinkaurelius.faunus.formats.titan.cassandra.FaunusTitanCassandraGraph.readFaunusVertex(FaunusTitanCassandraGraph.java:38)
        at com.thinkaurelius.faunus.formats.titan.cassandra.TitanCassandraRecordReader.nextKeyValue(TitanCassandraRecordReader.java:38)
        at org.apache.hadoop.mapred.MapTask$NewTrackingRecordReader.nextKeyValue(MapTask.java:532)
        at org.apache.hadoop.mapreduce.MapContext.nextKeyValue(MapContext.java:67)
        at org.apache.hadoop.mapreduce.Mapper.run(Mapper.java:143)
        at org.apache.hadoop.mapred.MapTask.runNewMapper(MapTask.java:764)
        at org.apache.hadoop.mapred.MapTask.run(MapTask.java:370)
        at org.apache.hadoop.mapred.LocalJobRunner$Job.run(LocalJobRunner.java:212)
13/03/01 04:36:08 INFO mapred.JobClient:  map 0% reduce 0%
13/03/01 04:36:08 INFO mapred.JobClient: Job complete: job_local_0001
13/03/01 04:36:08 INFO mapred.JobClient: Counters: 0
13/03/01 04:36:08 ERROR mapreduce.FaunusCompiler: Faunus job error -- remaining MapReduce jobs have been canceled
```

Above NPE will be thrown alternately.
I have tried deploy the system on Ubuntu and run same command, also tried connect the Titan DB from Ubuntu to RHEL, all works fine. The correct output:

``` java
gremlin> g.V.count()
13/03/01 04:48:54 INFO mapreduce.FaunusCompiler: Compiled to 1 MapReduce job(s)
13/03/01 04:48:54 INFO mapreduce.FaunusCompiler: Executing job 1 out of 1: MapSequence[com.thinkaurelius.faunus.mapreduce.transform.VerticesMap.Map, com.thinkaurelius.faunus.mapreduce.util.CountMapReduce.Map, com.thinkaurelius.faunus.mapreduce.util.CountMapReduce.Reduce]
13/03/01 04:48:54 INFO mapreduce.FaunusCompiler: Job data location: output/job-0
13/03/01 04:48:54 WARN util.NativeCodeLoader: Unable to load native-hadoop library for your platform... using builtin-java classes where applicable
13/03/01 04:48:54 WARN mapred.JobClient: Use GenericOptionsParser for parsing the arguments. Applications should implement Tool for the same.
13/03/01 04:48:55 INFO impl.ConnectionPoolMBeanManager: Registering mbean: com.netflix.MonitoredResources:type=ASTYANAX,name=TitanConnectionPool,ServiceType=connectionpool
13/03/01 04:48:55 WARN idassigner.VertexIDAssigner: ID Partitioning is disabled which will likely cause uneven data distribution
13/03/01 04:48:55 INFO mapred.JobClient: Running job: job_local_0001
13/03/01 04:48:55 INFO util.ProcessTree: setsid exited with exit code 0
13/03/01 04:48:55 INFO mapred.Task:  Using ResourceCalculatorPlugin : org.apache.hadoop.util.LinuxResourceCalculatorPlugin@70b6e675
13/03/01 04:48:55 WARN idassigner.VertexIDAssigner: ID Partitioning is disabled which will likely cause uneven data distribution
13/03/01 04:48:55 INFO mapred.MapTask: io.sort.mb = 100
13/03/01 04:48:56 INFO mapred.MapTask: data buffer = 79691776/99614720
13/03/01 04:48:56 INFO mapred.MapTask: record buffer = 262144/327680
13/03/01 04:48:56 ERROR impl.ConnectionPoolMBeanManager: com.netflix.MonitoredResources:type=ASTYANAX,name=TitanConnectionPool,ServiceType=connectionpool
13/03/01 04:48:56 INFO mapred.MapTask: Starting flush of map output
13/03/01 04:48:56 INFO compress.CodecPool: Got brand-new compressor
13/03/01 04:48:56 INFO mapred.Task: Task:attempt_local_0001_m_000000_0 is done. And is in the process of commiting
13/03/01 04:48:56 INFO mapred.JobClient:  map 0% reduce 0%
13/03/01 04:48:58 INFO mapred.LocalJobRunner:
13/03/01 04:48:58 INFO mapred.Task: Task 'attempt_local_0001_m_000000_0' done.
13/03/01 04:48:58 INFO mapred.Task:  Using ResourceCalculatorPlugin : org.apache.hadoop.util.LinuxResourceCalculatorPlugin@2ea089d4
13/03/01 04:48:58 INFO impl.ConnectionPoolMBeanManager: Registering mbean: com.netflix.MonitoredResources:type=ASTYANAX,name=TitanConnectionPool,ServiceType=connectionpool
13/03/01 04:48:58 WARN idassigner.VertexIDAssigner: ID Partitioning is disabled which will likely cause uneven data distribution
13/03/01 04:48:58 INFO mapred.MapTask: io.sort.mb = 100
13/03/01 04:48:59 INFO mapred.MapTask: data buffer = 79691776/99614720
13/03/01 04:48:59 INFO mapred.MapTask: record buffer = 262144/327680
13/03/01 04:48:59 ERROR impl.ConnectionPoolMBeanManager: com.netflix.MonitoredResources:type=ASTYANAX,name=TitanConnectionPool,ServiceType=connectionpool
13/03/01 04:48:59 INFO mapred.MapTask: Starting flush of map output
13/03/01 04:48:59 INFO mapred.Task: Task:attempt_local_0001_m_000001_0 is done. And is in the process of commiting
13/03/01 04:48:59 INFO mapred.JobClient:  map 100% reduce 0%
13/03/01 04:49:01 INFO mapred.LocalJobRunner:
13/03/01 04:49:01 INFO mapred.Task: Task 'attempt_local_0001_m_000001_0' done.
13/03/01 04:49:01 INFO mapred.Task:  Using ResourceCalculatorPlugin : org.apache.hadoop.util.LinuxResourceCalculatorPlugin@63a4c512
13/03/01 04:49:01 INFO mapred.LocalJobRunner:
13/03/01 04:49:01 INFO mapred.Merger: Merging 2 sorted segments
13/03/01 04:49:01 INFO compress.CodecPool: Got brand-new decompressor
13/03/01 04:49:01 INFO mapred.Merger: Down to the last merge-pass, with 0 segments left of total size: 0 bytes
13/03/01 04:49:01 INFO mapred.LocalJobRunner:
13/03/01 04:49:01 INFO mapred.Task: Task:attempt_local_0001_r_000000_0 is done. And is in the process of commiting
13/03/01 04:49:04 INFO mapred.LocalJobRunner: reduce > reduce
13/03/01 04:49:04 INFO mapred.Task: Task 'attempt_local_0001_r_000000_0' done.
13/03/01 04:49:05 INFO mapred.JobClient:  map 100% reduce 100%
13/03/01 04:49:05 INFO mapred.JobClient: Job complete: job_local_0001
13/03/01 04:49:05 INFO mapred.JobClient: Counters: 20
13/03/01 04:49:05 INFO mapred.JobClient:   File Output Format Counters
13/03/01 04:49:05 INFO mapred.JobClient:     Bytes Written=0
13/03/01 04:49:05 INFO mapred.JobClient:   FileSystemCounters
13/03/01 04:49:05 INFO mapred.JobClient:     FILE_BYTES_READ=139185694
13/03/01 04:49:05 INFO mapred.JobClient:     FILE_BYTES_WRITTEN=140391413
13/03/01 04:49:05 INFO mapred.JobClient:   File Input Format Counters
13/03/01 04:49:05 INFO mapred.JobClient:     Bytes Read=0
13/03/01 04:49:05 INFO mapred.JobClient:   Map-Reduce Framework
13/03/01 04:49:05 INFO mapred.JobClient:     Map output materialized bytes=28
13/03/01 04:49:05 INFO mapred.JobClient:     Map input records=0
13/03/01 04:49:05 INFO mapred.JobClient:     Reduce shuffle bytes=0
13/03/01 04:49:05 INFO mapred.JobClient:     Spilled Records=0
13/03/01 04:49:05 INFO mapred.JobClient:     Map output bytes=0
13/03/01 04:49:05 INFO mapred.JobClient:     Total committed heap usage (bytes)=989724672
13/03/01 04:49:05 INFO mapred.JobClient:     CPU time spent (ms)=0
13/03/01 04:49:05 INFO mapred.JobClient:     SPLIT_RAW_BYTES=134
13/03/01 04:49:05 INFO mapred.JobClient:     Combine input records=0
13/03/01 04:49:05 INFO mapred.JobClient:     Reduce input records=0
13/03/01 04:49:05 INFO mapred.JobClient:     Reduce input groups=0
13/03/01 04:49:05 INFO mapred.JobClient:     Combine output records=0
13/03/01 04:49:05 INFO mapred.JobClient:     Physical memory (bytes) snapshot=0
13/03/01 04:49:05 INFO mapred.JobClient:     Reduce output records=0
13/03/01 04:49:05 INFO mapred.JobClient:     Virtual memory (bytes) snapshot=0
13/03/01 04:49:05 INFO mapred.JobClient:     Map output records=0
```

**Comment by okram** [comment]
What version of Faunus and what version of Titan?

This happens when you use Faunus 0.1.0 with Titan 0.1.0. -- Yes, we know, the versions don't line up. They will have 1.0.

**Comment by wanghaifeng** [comment]
Both are 0.1.0, Thanks

**Comment by okram** [comment]
Titan 0.1.0 and Faunus 0.1-alpha work together.
Titan 0.2.0 and Faunus 0.1.0 work together.

https://github.com/thinkaurelius/faunus/wiki/Version-Compatibilities

Can you try again, please?

**Comment by okram** [comment]
Closing. This typically happens when Faunus 0.1.0 is trying to talk with Titan 0.1.0. Please reopen if still and issue.
