### ISSUE TITLE
Null checking in PropertyMapFilter. hasNot('x',null)

### ISSUE THREAD

**Issue by okram** [thinkaurelius/faunus#106]
java.lang.NullPointerException
        at com.thinkaurelius.faunus.mapreduce.filter.PropertyFilterMap.createConfiguration(PropertyFilterMap.java:36)
        at com.thinkaurelius.faunus.FaunusPipeline.has(FaunusPipeline.java:682)
        at com.thinkaurelius.faunus.FaunusPipeline.hasNot(FaunusPipeline.java:721)

**Comment by armisael** [comment]
Any hope to have this fixed soon?
Thanks!

**Comment by dkuppitz** [comment]
Just stumbled across this issue. For anybody who needs to workaround this issue:

``` Groovy
// g.V.has('foo', null) can be replaced by:
g.V.filter('{it.getProperty("foo")==null}')

// g.V.hasNot('foo', null) can be replaced by:
g.V.filter('{it.getProperty("foo")!=null}')
```

**Comment by spmallette** [comment]
The same goes for `has()` with null.
