### ISSUE TITLE
faunus count() problem with hbase as OutputFormat

### ISSUE THREAD

**Issue by ghost** [thinkaurelius/faunus#131]
Faunus 0.3.1 and 0.3.0

using the following properties file to initialize Faunus:

faunus.graph.input.format=com.thinkaurelius.faunus.formats.titan.hbase.TitanHBaseInputFormat
faunus.graph.input.titan.storage.backend=hbase
faunus.graph.input.titan.storage.hostname=<hostname>
faunus.graph.input.titan.storage.port=2181
faunus.graph.input.titan.storage.tablename=titan1

faunus.graph.output.format=com.thinkaurelius.faunus.formats.titan.hbase.TitanHBaseOutputFormat
faunus.graph.output.titan.storage.backend=hbase
faunus.graph.output.titan.storage.hostname=<hostname>
faunus.graph.output.titan.storage.port=2181
faunus.graph.output.titan.storage.tablename=titan2
faunus.graph.output.titan.storage.batch-loading=true
faunus.graph.output.titan.infer-schema=true
faunus.graph.output.blueprints.tx-commit=5000
faunus.sideeffect.output.format=org.apache.hadoop.mapreduce.lib.output.TextOutputFormat
faunus.output.location=faunustest1
faunus.output.location.overwrite=true

Problem is reproduced with the following steps:

./gremlin.sh
gremlin> g=FaunusFactory.open('./props.local')
==>faunusgraph[titanhbaseinputformat->titanhbaseoutputformat]
gremlin> g.V.count()
No more steps are possible as pipeline is locked
Display stack trace? [yN] n

Change the output format to anything but hbase:
g.setGraphOutputFormat(org.apache.hadoop.mapreduce.lib.output.SequenceFileOutputFormat.class)

gremlin> g.V.count()
......
==>8

produces result as expected.

Other output formats other than HBase also work with count().
Web page shows count() being a valid sideEffect in Faunus.
Appears sideeffect property is ignored when output format is hbase ?

**Comment by okram** [comment]
This is not a bug. If the output format is HBase, it goes through a series of MapReduce steps to bulk load the data (an Output/InputFormat in Faunus can have an arbitrary number of MapReduce jobs associated with it). Thus, you can not count() as the pipeline becomes locked for this process. Simply bulk load your data and then HBaseInput and count().

**Comment by varunkalluri** [comment]
Hi Okram,
I have integrated faunus with hdfs and titan with hbase, But  when we are trying to access data from titan into faunus it giving following error,

Here is my property file:
faunus.graph.input.format=com.thinkaurelius.faunus.formats.titan.hbase.TitanHBaseInputFormat
faunus.graph.input.titan.storage.backend=hbase
faunus.graph.input.titan.storage.hostname=xyz( I am specifying zookeeper hosts here)
faunus.graph.input.titan.storage.port=2181
faunus.graph.input.titan.storage.tablename=titan

faunus.graph.output.format=com.thinkaurelius.faunus.formats.titan.hbase.TitanHBaseOutputFormat
faunus.graph.output.titan.storage.backend=hbase
faunus.graph.output.titan.storage.hostname=xyz( I am specifying zookeeper hosts here)
faunus.graph.output.titan.storage.port=2181
faunus.graph.output.titan.storage.tablename=titan
faunus.graph.output.titan.storage.batch-loading=true
faunus.output.location=output1
zookeeper.znode.parent=/hbase-unsecure

# titan.graph.output.ids.block-size=100000

faunus.graph.output.titan.infer-schema=true

Execution:
 g = FaunusFactory.open('/opt/faunus/faunus-0.4.4/bin/titan-hbase-inputoutput.properties')
==>faunusgraph[titanhbaseinputformat->titanhbaseoutputformat]
gremlin> g.v(2640092)

13:24:20 WARN mapreduce.FaunusCompiler: Using the distribution Faunus job jar: ../lib/faunus-0.4.4-job.jar
13:24:21 INFO mapreduce.FaunusCompiler: Compiled to 3 MapReduce job(s)
13:24:21 INFO mapreduce.FaunusCompiler: Executing job 1 out of 3: MapSequence[com.thinkaurelius.faunus.mapreduce.transform.VertexMap.Map, com.thinkaurelius.faunus.formats.titan.SchemaInferencerMapReduce.Map, com.thinkaurelius.faunus.formats.titan.SchemaInferencerMapReduce.Reduce]
13:24:21 INFO mapreduce.FaunusCompiler: Job data location: output1/job-0
13:24:21 WARN mapred.JobClient: Use GenericOptionsParser for parsing the arguments. Applications should implement Tool for the same.
13:24:22 INFO diskstorage.Backend: Initiated backend operations thread pool of size 4
13:24:22 INFO zookeeper.ZooKeeper: Client environment:zookeeper.version=3.4.5-1392090, built on 09/30/2012 17:52 GMT
13:24:22 INFO zookeeper.ZooKeeper: Client environment:host.name=euca-192-168-216-107.eucalyptus.internal.devlab.dev
13:24:22 INFO zookeeper.ZooKeeper: Client environment:java.version=1.7.0_45
13:24:22 INFO zookeeper.ZooKeeper: Client environment:java.vendor=Oracle Corporation
13:24:22 INFO zookeeper.ZooKeeper: Client environment:java.home=/usr/java/jdk1.7.0_45/jre

13:24:24 INFO mapred.JobClient: Running job: job_201407181049_0009
13:24:25 INFO mapred.JobClient:  map 0% reduce 0%
13:30:04 INFO mapred.JobClient: Task Id : attempt_201407181049_0009_m_000000_0, Status : FAILED
com.thinkaurelius.titan.core.TitanException: Exception in Titan
        at com.thinkaurelius.titan.diskstorage.hbase.HBaseStoreManager.getAdminInterface(HBaseStoreManager.java:380)
        at com.thinkaurelius.titan.diskstorage.hbase.HBaseStoreManager.ensureColumnFamilyExists(HBaseStoreManager.java:275)
        at com.thinkaurelius.titan.diskstorage.hbase.HBaseStoreManager.openDatabase(HBaseStoreManager.java:228)
        at com.thinkaurelius.titan.diskstorage.Backend.getStore(Backend.java:231)
        at com.thinkaurelius.titan.diskstorage.Backend.initialize(Backend.java:243)
        at com.thinkaurelius.titan.graphdb.configuration.GraphDatabaseConfiguration.getBackend(GraphDatabaseConfiguration.java:1174)
        at com.thinkaurelius.titan.graphdb.database.StandardTitanGraph.<init>(StandardTitanGraph.java:75)
        at com.thinkaurelius.faunus.formats.titan.FaunusTitanGraph.<init>(FaunusTitanGraph.java:30)
        at com.thinkaurelius.faunus.formats.titan.FaunusTitanGraph.<init>(FaunusTitanGraph.java:26)
        at com.thinkaurelius.faunus.formats.titan.hbase.FaunusTitanHBaseGraph.<init>(FaunusTitanHBaseGraph.java:29)
        at com.thinkaurelius.faunus.formats.titan.hbase.TitanHBaseInputFormat.setConf(TitanHBaseInputFormat.java:53)
        at org.apache.hadoop.util.ReflectionUtils.setConf(ReflectionUtils.java:62)
        at org.apache.hadoop.util.ReflectionUtils.newInstance(ReflectionUtils.java:117)
        at org.apache.hadoop.mapred.MapTask.runNewMapper(MapTask.java:721)
        at org.apache.hadoop.mapred.MapTask.run(MapTask.java:363)
        at org.apache.hadoop.mapred.Child$4.run(Child.java:255)
        at java.security.AccessController.doPrivileged(Native Method)
        at javax.security.auth.Subject.doAs(Subject.java:415)
        at org.apache.hadoop.security.UserGroupInformation.doAs(UserGroupInformation.java:1232)
        at org.apache.hadoop.mapred.Child.main(Child.java:249)
Caused by: org.apache.hadoop.hbase.MasterNotRunningException: Retried 14 times
        at org.apache.hadoop.hbase.client.HBaseAdmin.<init>(HBaseAdmin.java:139)
        at com.thinkaurelius.titan.diskstorage.hbase.HBaseStoreManager.getAdminInterface(HBaseStoreManager.java:378)
        ... 19 more
13:46:45 INFO mapred.JobClient: Job complete: job_201407181049_0009
13:46:45 INFO mapred.JobClient: Counters: 8
13:46:45 INFO mapred.JobClient:   Job Counters
13:46:45 INFO mapred.JobClient:     SLOTS_MILLIS_MAPS=1334254
13:46:45 INFO mapred.JobClient:     Total time spent by all reduces waiting after reserving slots (ms)=0
13:46:45 INFO mapred.JobClient:     Total time spent by all maps waiting after reserving slots (ms)=0
13:46:45 INFO mapred.JobClient:     Rack-local map tasks=3
13:46:45 INFO mapred.JobClient:     Launched map tasks=4
13:46:45 INFO mapred.JobClient:     Data-local map tasks=1
13:46:45 INFO mapred.JobClient:     SLOTS_MILLIS_REDUCES=0
13:46:45 INFO mapred.JobClient:     Failed map tasks=1
13:46:45 ERROR mapreduce.FaunusCompiler: Faunus job error -- remaining MapReduce jobs have been canceled

please let me know if I am missing any configutions(or) settings.

Thanks,
varun

**Comment by shawny** [comment]
try :  g = FaunusFactory.open("faunus.properties") 
g.setGraphOutputFormat(NoOpOutputFormat.class)
g.V().count()
