### ISSUE TITLE
Kryo serliazation not respecting the bounds of a Double 64-bit.

### ISSUE THREAD

**Issue by okram** [thinkaurelius/faunus#140]
I create a N-Triple file:

```
<http://tinkerpop.com#1> <http://tinkerpop.com#name> "marko"^^<http://www.w3.org/2001/XMLSchema#string> .
<http://tinkerpop.com#1> <http://tinkerpop.com#age> "4.4579E13"^^<http://www.w3.org/2001/XMLSchema#double> .
```

I then run a simply Faunus script to get Marko's age.

```
~/software/aurelius/faunus$ bin/gremlin.sh

         \,,,/
         (o o)
-----oOOo-(_)-oOOo-----
2013-08-26 08:18:22.818 java[54690:1703] Unable to load realm info from SCDynamicStore
gremlin> hdfs.copyFromLocal('data/graph-example-1.ntriple','graph-example-1.ntriple')
==>null
gremlin> g = FaunusFactory.open('bin/rdf-input.properties')
==>faunusgraph[rdfinputformat->graphsonoutputformat]
gremlin> g.V.has('name','marko').age
08:19:06 WARN mapreduce.FaunusCompiler: Using the developer Faunus job jar: target/faunus-0.4.0-SNAPSHOT-job.jar
08:19:06 INFO mapreduce.FaunusCompiler: Compiled to 2 MapReduce job(s)
08:19:06 INFO mapreduce.FaunusCompiler: Executing job 1 out of 2: MapSequence[com.thinkaurelius.faunus.formats.edgelist.EdgeListInputMapReduce.Map, com.thinkaurelius.faunus.formats.edgelist.EdgeListInputMapReduce.Reduce]
08:19:06 INFO mapreduce.FaunusCompiler: Job data location: output/job-0
08:19:06 WARN mapred.JobClient: Use GenericOptionsParser for parsing the arguments. Applications should implement Tool for the same.
08:19:07 INFO input.FileInputFormat: Total input paths to process : 1
08:19:07 WARN util.NativeCodeLoader: Unable to load native-hadoop library for your platform... using builtin-java classes where applicable
08:19:07 WARN snappy.LoadSnappy: Snappy native library not loaded
08:19:07 INFO mapred.JobClient: Running job: job_201308220755_0007
08:19:08 INFO mapred.JobClient:  map 0% reduce 0%
08:19:15 INFO mapred.JobClient: Task Id : attempt_201308220755_0007_m_000000_0, Status : FAILED
java.io.IOException
    at com.thinkaurelius.faunus.mapreduce.MapSequence$Map.cleanup(MapSequence.java:96)
    at org.apache.hadoop.mapreduce.Mapper.run(Mapper.java:148)
    at org.apache.hadoop.mapred.MapTask.runNewMapper(MapTask.java:764)
    at org.apache.hadoop.mapred.MapTask.run(MapTask.java:364)
    at org.apache.hadoop.mapred.Child$4.run(Child.java:255)
    at java.security.AccessController.doPrivileged(Native Method)
    at javax.security.auth.Subject.doAs(Subject.java:415)
    at org.apache.hadoop.security.UserGroupInformation.doAs(UserGroupInformation.java:1190)
    at org.apache.hadoop.mapred.Child.main(Child.java:249)
Caused by: java.lang.reflect.InvocationTargetException
    at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
    at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:57)
    at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
    at java.lang.reflect.Method.invoke(Method.java:601)
    at com.thinkaurelius.faunus.mapreduce.MapSequence$Map.cleanup(MapSequence.java:93)
    ... 8 more
Caused by: java.lang.IllegalArgumentException: Double value is out of range: 4.4579E13
    at com.google.common.base.Preconditions.checkArgument(Preconditions.java:119)
    at com.thinkaurelius.titan.graphdb.database.serialize.attribute.DoubleSerializer.writeObjectData(DoubleSerializer.java:34)
    at com.thinkaurelius.titan.graphdb.database.serialize.attribute.DoubleSerializer.writeObjectData(DoubleSerializer.java:8)
    at com.thinkaurelius.titan.graphdb.database.serialize.kryo.KryoAttributeSerializerAdapter.write(KryoAttributeSerializerAdapter.java:26)
    at com.esotericsoftware.kryo.Kryo.writeClassAndObject(Kryo.java:568)
    at com.thinkaurelius.titan.graphdb.database.serialize.kryo.KryoDataOutput.writeClassAndObject(KryoDataOutput.java:85)
    at com.thinkaurelius.faunus.FaunusElement$ElementProperties.write(FaunusElement.java:244)
    at com.thinkaurelius.faunus.FaunusElement.write(FaunusElement.java:217)
    at com.thinkaurelius.faunus.FaunusVertex.write(FaunusVertex.java:280)
    at org.apache.hadoop.io.serializer.WritableSerialization$WritableSerializer.serialize(WritableSerialization.java:90)
    at org.apache.hadoop.io.serializer.WritableSerialization$WritableSerializer.serialize(WritableSerialization.java:77)
    at org.apache.hadoop.mapred.MapTask$MapOutputBuffer.collect(MapTask.java:1074)
    at org.apache.hadoop.mapred.MapTask$NewOutputCollector.write(MapTask.java:690)
    at org.apache.hadoop.mapreduce.TaskInputOutputContext.write(TaskInputOutputContext.java:80)
    at com.thinkaurelius.faunus.formats.edgelist.EdgeListInputMapReduce$Map.flush(EdgeListInputMapReduce.java:89)
    at com.thinkaurelius.faunus.formats.edgelist.EdgeListInputMapReduce$Map.cleanup(EdgeListInputMapReduce.java:83)
    ... 13 more
```

**Comment by dalaro** [comment]
DoubleSerializer uses a modified Long.MAX_VALUE and MIN_VALUE.  If I'm reading the code right, then it's dividing both values by (10^5 + 1).  I think the DoubleSerializer values are:

```
adjusted MIN_VALUE: -9.223362813491963E12
adjusted MAX_VALUE: 9.223362813491963E12
```

I don't understand the significance of this divisor at first glance.  Maybe reserving bits for another use, but then why not binary arithmetic?

**Comment by dalaro** [comment]
I think this may be related: https://github.com/thinkaurelius/titan/wiki/Titan-Limitations#double-and-float-data-types

Can you define the Titan type corresponding to age with the data type FullDouble instead of Double?

**Comment by okram** [comment]
Done.

**Comment by edi-bice** [comment]
I have the exact same problem (Faunus, DBPedia, Titan 0.4.4) and have tried what you suggested - created Titan property types with data type FullDouble instead of Double - but keep getting the same error. I assume it worked for you - can you please share the details of your type definition? Is it simply g.makeKey("age").dataType(FullDouble.class).make()
g.commit()
