### ISSUE TITLE
Exception when going from Titan HBase -> Titan HBase and infer-schema=false

### ISSUE THREAD

**Issue by erickt** [thinkaurelius/faunus#167]
cc @mbroecheler: this was the Faunus bug I mentioned when we last spoke.

I'm trying to use Faunus to read from a Titan HBase graph and write back to it. I've been able to get this to work with `infer-schema=true`, but when I disable it I get an exception in the mapreduce job. Here's my setup:

titan gremlin shell:

```
gremlin> g=TitanFactory.open('./conf/titan-hbase-es.properties')
2013-12-17 16:07:52.943 java[70657:1703] Unable to load realm info from SCDynamicStore
==>titangraph[hbase:127.0.0.1]
gremlin> GraphOfTheGodsFactory.load(g)
==>null
gremlin> g.commit()
==>null
```

faunus export-import.properties:

```
# input graph parameters
faunus.graph.input.format=com.thinkaurelius.faunus.formats.titan.hbase.TitanHBaseInputFormat
faunus.graph.input.titan.storage.backend=hbase
faunus.graph.input.titan.storage.hostname=localhost
faunus.graph.input.titan.storage.port=2181
faunus.graph.input.titan.storage.tablename=titan
faunus.graph.input.titan.storage.index.search.backend=elasticsearch
faunus.graph.input.titan.storage.index.search.hostname=localhost
faunus.graph.input.titan.storage.index.search.index-name=titan
faunus.graph.input.titan.storage.index.search.client-only=true
faunus.graph.input.titan.storage.index.search.local-mode=false
faunus.graph.input.vertex-query-filter=v.query().limit(0)

# output data (graph or statistic) parameters
faunus.graph.output.format=com.thinkaurelius.faunus.formats.titan.hbase.TitanHBaseOutputFormat
faunus.sideeffect.output.format=org.apache.hadoop.mapreduce.lib.output.TextOutputFormat
faunus.graph.output.titan.storage.backend=hbase
faunus.graph.output.titan.storage.hostname=localhost
faunus.graph.output.titan.storage.port=2181
faunus.graph.output.titan.storage.tablename=titan
faunus.graph.output.titan.storage.index.search.backend=elasticsearch
faunus.graph.output.titan.storage.index.search.hostname=localhost
faunus.graph.output.titan.storage.index.search.index-name=titan
faunus.graph.output.titan.storage.index.search.client-only=true
faunus.graph.output.titan.storage.index.search.local-mode=false
#faunus.graph.output.titan.storage.read-only=false
faunus.graph.output.titan.storage.batch-loading=false
faunus.graph.output.titan.infer-schema=false
faunus.graph.output.blueprints.script-file=import.groovy
faunus.output.location=import
faunus.output.location.overwrite=true
```

import.groovy:

```
import com.thinkaurelius.faunus.FaunusVertex
import com.tinkerpop.blueprints.Graph
import com.tinkerpop.blueprints.Vertex
import com.tinkerpop.blueprints.util.wrappers.id.IdGraph
import com.thinkaurelius.titan.graphdb.blueprints.TitanBlueprintsGraph
import com.thinkaurelius.titan.graphdb.database.StandardTitanGraph
import org.apache.hadoop.mapreduce.Mapper

import static com.thinkaurelius.faunus.formats.BlueprintsGraphOutputMapReduce.Counters.*
import static com.thinkaurelius.faunus.formats.BlueprintsGraphOutputMapReduce.LOGGER

def Vertex getOrCreateVertex(final FaunusVertex faunusVertex, final Graph graph, final Mapper.Context context) {
    Long id = faunusVertex.getIdAsLong();
    Vertex blueprintsVertex;

    try {
        blueprintsVertex = graph.getVertex(id);

        if (null == blueprintsVertex) {
            throw new RuntimeException("The vertex does not exist in Titan: " + faunusVertex);
        } else {
            context.getCounter(VERTICES_RETRIEVED).increment(1l);
            LOGGER.error("The titan vertex is found as: " + blueprintsVertex);
        }

        for (final String property : faunusVertex.getPropertyKeys()) {
            blueprintsVertex.setProperty(property, faunusVertex.getProperty(property));
            context.getCounter(VERTEX_PROPERTIES_WRITTEN).increment(1l);
        }

        LOGGER.error("The blueprints vertex is: " + blueprintsVertex);
    } catch(Exception e) {
        e.printStackTrace();
        throw e;
    }

    return blueprintsVertex;
}
```

Faunus gremlin shell:

```
gremlin> g=FaunusFactory.open('./export-import.properties')
==>faunusgraph[titanhbaseinputformat->titanhbaseoutputformat]
gremlin> g._
...
Error: java.io.IOException
    at com.thinkaurelius.faunus.mapreduce.MapSequence$Map.map(MapSequence.java:83)
    at com.thinkaurelius.faunus.mapreduce.MapSequence$Map.map(MapSequence.java:19)
    at org.apache.hadoop.mapreduce.Mapper.run(Mapper.java:144)
    at org.apache.hadoop.mapred.MapTask.runNewMapper(MapTask.java:756)
    at org.apache.hadoop.mapred.MapTask.run(MapTask.java:338)
    at org.apache.hadoop.mapred.YarnChild$2.run(YarnChild.java:157)
    at java.security.AccessController.doPrivileged(Native Method)
    at javax.security.auth.Subject.doAs(Subject.java:415)
    at org.apache.hadoop.security.UserGroupInformation.doAs(UserGroupInformation.java:1408)
    at org.apache.hadoop.mapred.YarnChild.main(YarnChild.java:152)
Caused by: java.lang.reflect.InvocationTargetException
    at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
    at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:57)
    at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
    at java.lang.reflect.Method.invoke(Method.java:606)
    at com.thinkaurelius.faunus.mapreduce.MapSequence$Map.map(MapSequence.java:79)
    ... 9 more
Caused by: java.io.IOException: javax.script.ScriptException: java.lang.UnsupportedOperationException: Cannot create new entities in read-only transaction
    at com.thinkaurelius.faunus.formats.BlueprintsGraphOutputMapReduce$VertexMap.map(BlueprintsGraphOutputMapReduce.java:149)
    ... 14 more
Caused by: java.lang.InterruptedException: javax.script.ScriptException: java.lang.UnsupportedOperationException: Cannot create new entities in read-only transaction
    at com.thinkaurelius.faunus.formats.BlueprintsGraphOutputMapReduce$VertexMap.getOrCreateVertex(BlueprintsGraphOutputMapReduce.java:187)
    at com.thinkaurelius.faunus.formats.BlueprintsGraphOutputMapReduce$VertexMap.map(BlueprintsGraphOutputMapReduce.java:128)
    ... 14 more
```

**Comment by okram** [comment]
This seems to be a Titan issue around "thinking its in read-only mode," where the read InputFormat and the write OutputFormat TitanGraph connections "see each other" ??? I didn't dig any deeper than just to, in Faunus 0.5.0, remove read-only=true as a parameter in TitanXXXInputFormat. As a work around for you, simply read from HBase, then write to SequenceFile. Then read from SequenceFile and write to HBase (two separate faunus.properties files).
