### ISSUE TITLE
Better ID and LABEL handling throughout Faunus data pipelines.

### ISSUE THREAD

**Issue by okram** [thinkaurelius/faunus#92]
java.lang.IllegalArgumentException: Name is reserved: label
    at com.thinkaurelius.titan.graphdb.types.StandardTypeMaker.checkGeneralArguments(StandardTypeMaker.java:60)
    at com.thinkaurelius.titan.graphdb.types.StandardTypeMaker.makePropertyKey(StandardTypeMaker.java:100)
    at com.thinkaurelius.titan.graphdb.blueprints.BlueprintsDefaultTypeMaker.makeKey(BlueprintsDefaultTypeMaker.java:21)
    at com.thinkaurelius.faunus.formats.titan.SchemaInferencerMapReduce$Reduce.reduce(SchemaInferencerMapReduce.java:86)
    at com.thinkaurelius.faunus.formats.titan.SchemaInferencerMapReduce$Reduce.reduce(SchemaInferencerMapReduce.java:66)
    at org.apache.hadoop.mapreduce.Reducer.run(Reducer.java:176)
    at org.apache.hadoop.mapred.ReduceTask.runNewReducer(ReduceTask.java:650)
    at org.apache.hadoop.mapred.ReduceTask.run(ReduceTask.java:418)
    at org.apache.hadoop.mapred.Child$4.run(Child.java:255)
    at java.security.AccessController.doPrivileged(Native Method)
    at javax.security.auth.Subject.doAs(Subject.java:416)
    at org.apache.hadoop.security.UserGroupInformation.doAs(UserGroupInformation.java:1136)
    at org.apache.hadoop.mapred.Child.main(Child.java:249)

**Comment by PhaedrusTheGreek** [comment]
I am also running into this problem trying to import a database into Titan that I have been running successfully on OrientDB.  Is there a workaround other than renaming my "LABEL" vertex property?

Thanks,

Jay

**Comment by okram** [comment]
The world "label" and "id" are reserved. You will have to rename the vertex property.
