### ISSUE TITLE
Thrift frame exception with Cassandra unable to be overcome with more memory..?

### ISSUE THREAD

**Issue by okram** [thinkaurelius/faunus#99]
There is an exception that occurs with TitanCassandraInputFormat when using the plain vanilla, default properties in Faunus/Hadoop and you reach a vertex that has a large number of edges (a super node). I decided to isolate this problem, test it, and try to overcome it. Here is my story.

```
1. I created a graph with a single vertex with X incident edges. To create that vertex, I open Gremlin/Titan/Cassandra and ran this code with x being the variable determining the number of edges for the vertex.

    -------------------------------------------------------------------------------
g = TitanFactory.open('bin/cassandra.local')
x = 10000 // the number of edges for the vertex
v = g.addVertex()
(1..x).each{ g.addEdge(v,v,'link'); 
  if(it % 1000 == 0) {
    g.stopTransaction(SUCCESS) 
    v = g.v(v.id)
  }
}; null;
g.stopTransaction(SUCCESS)
    -------------------------------------------------------------------------------

2. I then used the default titan-cassandra-input.properties provided by Faunus. Next, I jumped into Gremlin/Faunus and ran the following query:
    g.E.count()

3. Here are the runtimes for the various experimental runs (as I wipe the graph and create a new vertex with more edges). 
    * Note that most of this time is basically Hadoop starting up.
    * Note that this is with Titan/Cassandra on localhost along with Hadoop (MacBook Pro -- retina display, baby)

    10 edges : 14 seconds
    100 edges : 14 seconds
    1000 edges : 14 seconds
    10000 edges : 13 seconds
    100000 edges : 15 seconds
    1000000 edges : Thrift Frame Exception !

4. Keeping default properties, I wanted to see where this broke between 100k and 1M edges.

    200000 edges : 15 seconds
    300000 edges : 15 seconds
    400000 edges : 16 seconds
    500000 edges : Thrift Frame Exception !
```

… this is as far as I got. It looks like 500k edges (1M incident -- in and out) is what we can currently support for a vertex. One of the most odd things is that up'ing the following cassandra.yaml properties does nothing:

```
thrift_framed_transport_size_in_mb: 999 
thrift_max_message_length_in_mb: 1000
```

Things I've tested:
    - g.getConfiguration().setBoolean('cassandra.input.widerows',true)
    - g.getConfiguration().set('cassandra.range.batch.size','16')  
..to no avail.

Also, there is nothing on the Cassandra mailing list that mentions a solution -- save a previous question of mine :).

**Comment by okram** [comment]
I have a semi-solution to this problem.

So I loaded 1 million edges onto a vertex (given the code fragment from previous). Thus, there are 2 million incident edge as the edges are self-loops (in = 1M, out = 1M, both = 2M).

I do a normal load and we get the same Thrift Frame Exception. However, now, I can do this (or have it in my faunus.properties):

gremlin> g.getConfiguration().setInt("cassandra.range.batch.size",200000)
==>null
gremlin> g.getProperties('cassandra')
==>cassandra.range.batch.size=200000
==>cassandra.input.partitioner.class=org.apache.cassandra.dht.RandomPartitioner

If I set this lower, in the Faunus code, I use this here (before it was always set to Integer.MAX_VALUE). 

```
https://github.com/thinkaurelius/faunus/blob/master/src/main/java/com/thinkaurelius/faunus/formats/titan/cassandra/TitanCassandraInputFormat.java#L58
```

No more exception, but:

…
13/01/18 14:13:12 INFO mapred.JobClient:     OUT_EDGES_PROCESSED=199999
13/01/18 14:13:12 INFO mapred.JobClient:   File Output Format Counters 
13/01/18 14:13:12 INFO mapred.JobClient:     Bytes Written=0
13/01/18 14:13:12 INFO mapred.JobClient:   com.thinkaurelius.faunus.mapreduce.util.CountMapReduce$Counters
13/01/18 14:13:12 INFO mapred.JobClient:     EDGES_COUNTED=199999
13/01/18 14:13:12 INFO mapred.JobClient:   FileSystemCounters
13/01/18 14:13:12 INFO mapred.JobClient:     FILE_BYTES_READ=29
13/01/18 14:13:12 INFO mapred.JobClient:     HDFS_BYTES_READ=210
13/01/18 14:13:12 INFO mapred.JobClient:     FILE_BYTES_WRITTEN=84144
13/01/18 14:13:12 INFO mapred.JobClient:     HDFS_BYTES_WRITTEN=7
13/01/18 14:13:12 INFO mapred.JobClient:   File Input Format Counters 
13/01/18 14:13:12 INFO mapred.JobClient:     Bytes Read=0
13/01/18 14:13:12 INFO mapred.JobClient:   Map-Reduce Framework
13/01/18 14:13:12 INFO mapred.JobClient:     Reduce input groups=1
13/01/18 14:13:12 INFO mapred.JobClient:     Map output materialized bytes=35
13/01/18 14:13:12 INFO mapred.JobClient:     Combine output records=1
13/01/18 14:13:12 INFO mapred.JobClient:     Map input records=1
13/01/18 14:13:12 INFO mapred.JobClient:     Reduce shuffle bytes=35
13/01/18 14:13:12 INFO mapred.JobClient:     Reduce output records=0
13/01/18 14:13:12 INFO mapred.JobClient:     Spilled Records=2
13/01/18 14:13:12 INFO mapred.JobClient:     Map output bytes=8
13/01/18 14:13:12 INFO mapred.JobClient:     Total committed heap usage (bytes)=477888512
13/01/18 14:13:12 INFO mapred.JobClient:     Combine input records=1
13/01/18 14:13:12 INFO mapred.JobClient:     Map output records=1
13/01/18 14:13:12 INFO mapred.JobClient:     SPLIT_RAW_BYTES=210
13/01/18 14:13:12 INFO mapred.JobClient:     Reduce input records=1
==>199999

:). Anywho… As such, seems we can do ~400k as the range.batch.size before Cassandra barfs with the Thirft exception (note, the edges have no properties so smaller than if they did have properties).

**Comment by xedin** [comment]
@okram can you please also add exception stack-trace to this ticket?

**Comment by okram** [comment]
13/01/21 13:08:25 INFO mapred.JobClient: Task Id : attempt_201301181412_0065_m_000001_0, Status : FAILED
java.lang.RuntimeException: org.apache.thrift.transport.TTransportException: Frame size (21592015) larger than max length (16384000)!
    at org.apache.cassandra.hadoop.ColumnFamilyRecordReader$StaticRowIterator.maybeInit(ColumnFamilyRecordReader.java:400)
    at org.apache.cassandra.hadoop.ColumnFamilyRecordReader$StaticRowIterator.computeNext(ColumnFamilyRecordReader.java:406)
    at org.apache.cassandra.hadoop.ColumnFamilyRecordReader$StaticRowIterator.computeNext(ColumnFamilyRecordReader.java:324)
    at com.google.common.collect.AbstractIterator.tryToComputeNext(AbstractIterator.java:143)
    at com.google.common.collect.AbstractIterator.hasNext(AbstractIterator.java:138)
    at org.apache.cassandra.hadoop.ColumnFamilyRecordReader.nextKeyValue(ColumnFamilyRecordReader.java:189)
    at com.thinkaurelius.faunus.formats.titan.cassandra.TitanCassandraRecordReader.nextKeyValue(TitanCassandraRecordReader.java:37)
    at org.apache.hadoop.mapred.MapTask$NewTrackingRecordReader.nextKeyValue(MapTask.java:532)
    at org.apache.hadoop.mapreduce.MapContext.nextKeyValue(MapContext.java:67)
    at org.apache.hadoop.mapreduce.Mapper.run(Mapper.java:143)
    at org.apache.hadoop.mapred.MapTask.runNewMapper(MapTask.java:764)
    at org.apache.hadoop.mapred.MapTask.run(MapTask.java:370)
    at org.apache.hadoop.mapred.Child$4.run(Child.java:255)
    at java.security.AccessController.doPrivileged(Native Method)
    at javax.security.auth.Subject.doAs(Subject.java:415)
    at org.apache.hadoop.security.UserGroupInformation.doAs(UserGroupInformation.java:1136)
    at org.apache.hadoop.mapred.Child.main(Child.java:249)
Caused by: org.apache.thrift.transport.TTransportException: Frame size (21592015) larger than max length (16384000)!
    at org.apache.thrift.transport.TFramedTransport.readFrame(TFramedTransport.java:137)
    at org.apache.thrift.transport.TFramedTransport.read(TFramedTransport.java:101)
    at org.apache.thrift.transport.TTransport.readAll(TTransport.java:84)
    at org.apache.thrift.protocol.TBinaryProtocol.readAll(TBinaryProtocol.java:378)
    at org.apache.thrift.protocol.TBinaryProtocol.readI32(TBinaryProtocol.java:297)
    at org.apache.thrift.protocol.TBinaryProtocol.readMessageBegin(TBinaryProtocol.java:204)
    at org.apache.thrift.TServiceClient.receiveBase(TServiceClient.java:69)
    at org.apache.cassandra.thrift.Cassandra$Client.recv_get_range_slices(Cassandra.java:692)
    at org.apache.cassandra.thrift.Cassandra$Client.get_range_slices(Cassandra.java:676)
    at org.apache.cassandra.hadoop.ColumnFamilyRecordReader$StaticRowIterator.maybeInit(ColumnFamilyRecordReader.java:357)
    ... 16 more

**Comment by okram** [comment]
Done. Thanks @xedin
